DROP TABLE IF EXISTS MEDIA_SUBTITLE;
CREATE TABLE MEDIA_SUBTITLE
(
    CONTENT_ID BIGINT PRIMARY KEY NOT NULL,
    LANGUAGE_CODE_2 VARCHAR(2),
    SUBTITLE_ID BIGINT,
    CONSTRAINT FK_SUBTITLE FOREIGN KEY (SUBTITLE_ID) REFERENCES SUBTITLE (ID)
);