spring:
  data:
    rest:
      base-path: /rest
  application:
    name: language-ms
  datasource:
    url: jdbc:postgresql://localhost:5432/araok-language
    username: araok
    password: araok
    driver-class-name: org.postgresql.Driver

  flyway:
    baseline-on-migrate: true
    enabled: true
    url: jdbc:postgresql://localhost:5432/araok-language
    user: araok
    password: araok

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

server:
  port: 8091